# Strings and chord.
string notes: 'E2,A2,D3,G3,C4,F4'
number of frets: 12
capo fret: 0  
chord: 'C'

# Graphical options.
show note names: yes
show realistic frets: yes
use neural network: yes     
save images: no
image format: 'jpg'

# Some options for string tunings:
# E2,A2,D3,G3,B3,E4  # guitar, standard
# E2,A2,D3,G3,C4,F4  # guitar, all fourths
# E2,G#2,C3,E3,G#3,C4,E4  # 7-strings guitar, all thirds
# E2,G#2,C3,E3,G#3,C4  # guitar, all thirds
# E1,A1,D2,G2  # bass, standard
# G3,C3,E3,A3  # ukelele, standard

# Chord examples:
# C, C7, Caug, Dm, Eb, Em, E5, F, FM7, G7, Am7, Bdis, Bb, Cbm, C5
# Equivalence eamples:
# C = (C,E,G)'
# G7 = (G,B,D,F)
# Eb = (Eb,G,Bb)
# E5 = (E,B)
